# Generated by Django 4.2.1 on 2023-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('preview_text', models.TextField(max_length=300)),
                ('content', models.TextField(max_length=1500)),
                ('date', models.DateTimeField(auto_now=True)),
                ('preview_image', models.ImageField(upload_to='posts_images/')),
            ],
        ),
    ]
