# Generated by Django 4.2.1 on 2023-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('preview_text', models.TextField(max_length=300)),
                ('preview_image', models.ImageField(upload_to='portfolio_images/')),
                ('url', models.URLField()),
            ],
        ),
    ]
